### ISSUE TITLE
Improve default stack traces display

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/friendly-error#5]
Current stack trace:

```
Error: Error message asinc whadoop
    at asinc (/home/david/projects/friendly-error/test/base.js:8:27)
    at Object.<anonymous> (/home/david/projects/friendly-error/test/base.js:11:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

Problems :
- useless repeated `at`
- no "table structure", making it hard to find the files
- no content priorisation (column number matters less than line)
- useless node-internal info

**Comment by DavidBruant** [comment]
https://github.com/AriaMinaei/pretty-error/blob/master/src/nodePaths.coffee
